# 本地环境，存储服务在AWS，已经通过腾讯云做了端口转发，网络好的话可以直接连13.230.161.7
logging:
  path: G:/logs
spring:
  datasource:
#    url: jdbc:mysql://13.230.161.7:3306/test
    url: jdbc:mysql://118.24.212.141:3306/test
    username: test
    password: 12345678
  redis:
#    host: 13.230.161.7
    host: 118.24.212.141
    port: 6379
    password:
  rabbitmq:
#    host: 13.230.161.7
    host: 118.24.212.141
    port: 5672
    username: guest
    password: guest
filepath: G:/fileupload