logging:
  path: /data/logs/prod
spring:
  datasource:
    url: jdbc:mysql://13.230.161.7:3306/prod
    username: prod
    password: 12345678
  redis:
    host: 13.230.161.7
    port: 6379
    password:
  rabbitmq:
    host: 13.230.161.7
    port: 5672
    username: guest
    password: guest
filepath: /data/fileupload