spring:
  profiles:
    active: test
  application:
    name: qblog
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  servlet:
    multipart:
      # springboot内嵌容器限制上传单个文件1M，一次请求10M
      max-file-size: 10MB
      max-request-size: 100MB
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.qiaohx.qblog.service.*.model
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
qiniu:
  appkey: dowerBuOZWW7yKxiJHj2ssvTqAhX-xGaoNZQsXoU
  appsecret: ekWKVFM3AIAye2ueTy8H9ciPROYRZEF128DnaxQn
  bucket: qblog
  baseurl: http://image.qiaohx.com/