logging:
  path: /data/logs/test
spring:
  datasource:
    url: jdbc:mysql://13.230.161.7:3306/test
    username: test
    password: 12345678
  redis:
    host: 13.230.161.7
    port: 6379
    password: