package com.qiaohx.qblog.service.user.model;

import java.io.Serializable;
import java.util.Date;

public class UserLoginCert implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_cert.LOGIN_CERT_ID
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    private String loginCertId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_cert.USER_ID
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_cert.CERT_TYPE
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    private String certType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_cert.LOGIN_CERT
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    private String loginCert;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_cert.PASSWORD
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_cert.FLAG
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    private String flag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_cert.CREATE_DATE
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_login_cert.UPDATE_DATE
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    private Date updateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_login_cert
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_cert.LOGIN_CERT_ID
     *
     * @return the value of user_login_cert.LOGIN_CERT_ID
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public String getLoginCertId() {
        return loginCertId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_cert.LOGIN_CERT_ID
     *
     * @param loginCertId the value for user_login_cert.LOGIN_CERT_ID
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public void setLoginCertId(String loginCertId) {
        this.loginCertId = loginCertId == null ? null : loginCertId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_cert.USER_ID
     *
     * @return the value of user_login_cert.USER_ID
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_cert.USER_ID
     *
     * @param userId the value for user_login_cert.USER_ID
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_cert.CERT_TYPE
     *
     * @return the value of user_login_cert.CERT_TYPE
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public String getCertType() {
        return certType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_cert.CERT_TYPE
     *
     * @param certType the value for user_login_cert.CERT_TYPE
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public void setCertType(String certType) {
        this.certType = certType == null ? null : certType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_cert.LOGIN_CERT
     *
     * @return the value of user_login_cert.LOGIN_CERT
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public String getLoginCert() {
        return loginCert;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_cert.LOGIN_CERT
     *
     * @param loginCert the value for user_login_cert.LOGIN_CERT
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public void setLoginCert(String loginCert) {
        this.loginCert = loginCert == null ? null : loginCert.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_cert.PASSWORD
     *
     * @return the value of user_login_cert.PASSWORD
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_cert.PASSWORD
     *
     * @param password the value for user_login_cert.PASSWORD
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_cert.FLAG
     *
     * @return the value of user_login_cert.FLAG
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public String getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_cert.FLAG
     *
     * @param flag the value for user_login_cert.FLAG
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public void setFlag(String flag) {
        this.flag = flag == null ? null : flag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_cert.CREATE_DATE
     *
     * @return the value of user_login_cert.CREATE_DATE
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_cert.CREATE_DATE
     *
     * @param createDate the value for user_login_cert.CREATE_DATE
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_login_cert.UPDATE_DATE
     *
     * @return the value of user_login_cert.UPDATE_DATE
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_login_cert.UPDATE_DATE
     *
     * @param updateDate the value for user_login_cert.UPDATE_DATE
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}