package com.qiaohx.qblog.service.user.dao;

import com.qiaohx.qblog.service.user.model.UserLoginCert;

public interface UserLoginCertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_cert
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    int insert(UserLoginCert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_cert
     *
     * @mbggenerated Mon Mar 25 21:41:06 CST 2019
     */
    int insertSelective(UserLoginCert record);
}